FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev gcc \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app/dbt

COPY requirements-dbt.txt .
RUN pip install --no-cache-dir -r requirements-dbt.txt

COPY dbt/ .

ENTRYPOINT ["dbt"]
CMD ["build", "--profiles-dir", "."]
